name: CI Pipeline Example

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run a simple test
        run: |
          echo "Starting CI pipeline..."
          python -c "print('All tests passed successfully! ✅')"
